### ISSUE TITLE
Bug 回报：Kratos-Rebirth\scripts\friends.js渲染？

### ISSUE THREAD

**Issue by greenhandzdl** [Candinya/Kratos-Rebirth#120]
# 错误详情
```
INFO  Validating config
INFO  DPlayer.min.css is not found in this version of dplayer, skip it.
INFO  Start processing
update link as:-->/2022/02/10/fan-bian-yi/dui-unity-de-windows-xiang-mu-jin-xing-dll-fan-bian-yi-xiu-gai/%E9%A1%B9%E7%9B%AE%E5%85%A8%E6%99%AF.png
update link as:-->/2022/02/10/fan-bian-yi/dui-unity-de-windows-xiang-mu-jin-xing-dll-fan-bian-yi-xiu-gai/ILSpy%E7%95%8C%E9%9D%A2%E8%AE%B2%E8%A7%A3.jpg
update link as:-->/2022/02/10/fan-bian-yi/dui-unity-de-windows-xiang-mu-jin-xing-dll-fan-bian-yi-xiu-gai/VS%E7%95%8C%E9%9D%A2%E9%83%A8%E5%88%86.jpg
update link as:-->/2022/02/10/fan-bian-yi/dui-unity-de-windows-xiang-mu-jin-xing-dll-fan-bian-yi-xiu-gai/%E9%A1%B9%E7%9B%AE%E5%85%A8%E6%99%AF.png
update link as:-->/2022/02/10/fan-bian-yi/dui-unity-de-windows-xiang-mu-jin-xing-dll-fan-bian-yi-xiu-gai/ILSpy%E7%95%8C%E9%9D%A2%E8%AE%B2%E8%A7%A3.jpg
update link as:-->/2022/02/10/fan-bian-yi/dui-unity-de-windows-xiang-mu-jin-xing-dll-fan-bian-yi-xiu-gai/VS%E7%95%8C%E9%9D%A2%E9%83%A8%E5%88%86.jpg
update link as:-->/2020/10/03/jian-zhan/wordpress/termux-chuang-jian-wordpress-wang-zhan/%E7%A4%BA%E4%BE%8B%E5%9B%BE.pngupdate link as:-->/2020/10/03/jian-zhan/wordpress/termux-chuang-jian-wordpress-wang-zhan/%E7%A4%BA%E4%BE%8B%E5%9B%BE.pngupdate link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/start.png
update link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/1.png
update link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/2.png
update link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/3.png
update link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/4.png
update link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/5.png
update link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/6.png
update link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/7.png
update link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/8.png
update link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/9.png
update link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/end_1.png
update link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/end_2.png
update link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/end_3.png
update link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/end_4.png
update link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/start.png
update link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/1.png
update link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/2.png
update link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/3.png
update link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/4.png
update link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/5.png
update link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/6.png
update link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/7.png
update link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/8.png
update link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/9.png
update link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/end_1.png
update link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/end_2.png
update link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/end_3.png
update link as:-->/2020/09/06/you-xi/plague-inc/pl-w-1/end_4.png
INFO  Generating Baidu urls for last 200 posts
INFO  Posts urls generated in urls.txt
https://greenhandzdl.github.io/2022/03/31/translate/william-shakespeare/hamlet/to-be-or-not-to-be-fan-yi-chang-shi/
https://greenhandzdl.github.io/2022/02/10/fan-bian-yi/dui-unity-de-windows-xiang-mu-jin-xing-dll-fan-bian-yi-xiu-gai/
https://greenhandzdl.github.io/2020/12/12/linux/selinux/selinux/
https://greenhandzdl.github.io/2020/11/25/android/termux/ru-he-zai-termux-bu-zhi-chi-de-ban-ben-an-zhuang-gh/
https://greenhandzdl.github.io/2020/11/19/nodejs/plugins/npm-gao-ji-yong-fa/
https://greenhandzdl.github.io/2020/11/14/android/ru-he-root-ni-de-shou-ji/
https://greenhandzdl.github.io/2020/11/09/android/termux/ru-he-zai-shou-ji-kuai-su-da-jian-linux/
https://greenhandzdl.github.io/2020/10/19/linux/shi-yong-gong-ju/linux-shi-yong-gong-ju/
https://greenhandzdl.github.io/2020/10/03/jian-zhan/wordpress/termux-chuang-jian-wordpress-wang-zhan/
https://greenhandzdl.github.io/2020/10/01/sui-bi-ji/sui-bi-ji/
https://greenhandzdl.github.io/2020/10/01/jian-zhan/hexo/plugins/hexo-git-backup-de-bao-cuo/
https://greenhandzdl.github.io/2020/09/21/jian-zhan/hexo/termux-jian-yi-jian-zhan/
https://greenhandzdl.github.io/2020/09/08/linux/wine/ab-wine/
https://greenhandzdl.github.io/2020/09/07/you-xi/minecraft/min-inst/
https://greenhandzdl.github.io/2020/09/06/you-xi/plague-inc/pl-w-1/
FATAL {
  err: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:370:5)
      at onParseError (node:internal/url:536:9)
      at new URL (node:internal/url:612:5)
      at request (node:https:339:32)
      at Object.get (node:https:387:15)
      at D:\Users\20292\Documents\GitHub\hexo.bak\themes\Kratos-Rebirth\scripts\friends.js:64:15
      at Array.forEach (<anonymous>)
      at Hexo.<anonymous> (D:\Users\20292\Documents\GitHub\hexo.bak\themes\Kratos-Rebirth\scripts\friends.js:63:18)
      at Object.onceWrapper (node:events:513:28)
      at Hexo.emit (node:events:406:35)
      at D:\Users\20292\Documents\GitHub\hexo.bak\node_modules\hexo\lib\hexo\index.js:451:14
      at tryCatcher (D:\Users\20292\Documents\GitHub\hexo.bak\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (D:\Users\20292\Documents\GitHub\hexo.bak\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (D:\Users\20292\Documents\GitHub\hexo.bak\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (D:\Users\20292\Documents\GitHub\hexo.bak\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (D:\Users\20292\Documents\GitHub\hexo.bak\node_modules\bluebird\js\release\promise.js:729:18)
      at Promise._fulfill (D:\Users\20292\Documents\GitHub\hexo.bak\node_modules\bluebird\js\release\promise.js:673:18)
      at Promise._resolveCallback (D:\Users\20292\Documents\GitHub\hexo.bak\node_modules\bluebird\js\release\promise.js:466:57)
      at Promise._settlePromiseFromHandler (D:\Users\20292\Documents\GitHub\hexo.bak\node_modules\bluebird\js\release\promise.js:559:17)
      at Promise._settlePromise (D:\Users\20292\Documents\GitHub\hexo.bak\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (D:\Users\20292\Documents\GitHub\hexo.bak\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (D:\Users\20292\Documents\GitHub\hexo.bak\node_modules\bluebird\js\release\promise.js:729:18)
      at Promise._fulfill (D:\Users\20292\Documents\GitHub\hexo.bak\node_modules\bluebird\js\release\promise.js:673:18)
      at MappingPromiseArray.PromiseArray._resolve (D:\Users\20292\Documents\GitHub\hexo.bak\node_modules\bluebird\js\release\promise_array.js:127:19)
      at MappingPromiseArray._promiseFulfilled (D:\Users\20292\Documents\GitHub\hexo.bak\node_modules\bluebird\js\release\map.js:108:18)
      at Promise._settlePromise (D:\Users\20292\Documents\GitHub\hexo.bak\node_modules\bluebird\js\release\promise.js:609:26)
      at Promise._settlePromise0 (D:\Users\20292\Documents\GitHub\hexo.bak\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (D:\Users\20292\Documents\GitHub\hexo.bak\node_modules\bluebird\js\release\promise.js:729:18) {
    input: '#',
    code: 'ERR_INVALID_URL'
  }
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html
INFO  感谢使用 Kratos-Rebirth 主题，您的版本是 v1.8.1
INFO  如有任何疑问，您可以查阅文档，或是去 https://github.com/Candinya/Kratos-Rebirth/issues 提出对应的 issue 。
INFO  预祝您使用愉快。
```
# Nodejs版本
```
PS C:\Users\20292> node -v
v16.5.0
```
# 复现？
* 拉到最新的pr

**Comment by greenhandzdl** [comment]
无效操作：
* 撤回cbe7872

**Comment by Candinya** [comment]
请检查您的友链列表，请注意之前样例模板中的 `#` 并不是一个有效的 URL 字符串

**Comment by greenhandzdl** [comment]
也就是后面几个版本不允许#注释链接了？

**Comment by Candinya** [comment]
> 也就是后面几个版本不允许#注释链接了？

嗯，因为这个不知道为什么在之前的检查中没有触发问题，但现在确实是不推荐这么做了（因为严格意义上来讲这算是失去意义的链接，但会追加一个修复，跳过这些无效的链接）
