### ISSUE TITLE
Bug 回报：运行报错

### ISSUE THREAD

**Issue by OcrSu** [Candinya/Kratos-Rebirth#209]
### 报告前须知

- [X] 我确认该 Bug 是可复现的，我会根据下面的模板提供完整详尽的复现步骤
- [X] 我确认已认真阅读 ReadMe.md 和 文档，确认描述的内容有误或是不能解决我的问题
- [X] 我已知晓如果没有认真阅读且勾选这里所有的条目，或是没有使用此模板认真详细地描述问题，是对彼此时间的浪费，我的 issue 可能会被无解释关闭

### 安装方式

使用 npm 等包管理工具安装至 node_modules 目录下

### 对 Bug 的描述

$ hexo s
INFO  Validating config
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object
    at Object.extname (node:path:905:5)
    at Hexo.<anonymous> (D:\ServerCore\blog-lsw\node_modules\hexo-theme-kratos-rebirth\scripts\search.js:19:16)
    at Object.onceWrapper (node:events:633:28)
    at Hexo.emit (node:events:531:35)
    at Hexo._generate (D:\ServerCore\blog-lsw\node_modules\hexo\dist\hexo\index.js:380:14)
    at D:\ServerCore\blog-lsw\node_modules\hexo\dist\hexo\index.js:298:25
    at tryCatcher (D:\ServerCore\blog-lsw\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\ServerCore\blog-lsw\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\ServerCore\blog-lsw\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\ServerCore\blog-lsw\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\ServerCore\blog-lsw\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (D:\ServerCore\blog-lsw\node_modules\bluebird\js\release\promise.js:673:18)
    at PromiseArray._resolve (D:\ServerCore\blog-lsw\node_modules\bluebird\js\release\promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (D:\ServerCore\blog-lsw\node_modules\bluebird\js\release\promise_array.js:145:14)
    at Promise._settlePromise (D:\ServerCore\blog-lsw\node_modules\bluebird\js\release\promise.js:609:26)
    at Promise._settlePromise0 (D:\ServerCore\blog-lsw\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\ServerCore\blog-lsw\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\ServerCore\blog-lsw\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\ServerCore\blog-lsw\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\ServerCore\blog-lsw\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (D:\ServerCore\blog-lsw\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:483:21)

### 复现的方法

1.在空白文件夹内打开Git Bash

2.执行以下命令
$ hexo init blog-lsw
$ cd blog-lsw
$ npm install
$ npm install hexo-theme-kratos-rebirth

3. copy 仓库中的config.yml到博客目录，并重命名为_config.kratos-rebirth.yml

4. 执行hexo s指令

然后就报错了

### 期望的行为

正常运行博客

### 相关的截图

![image](https://github.com/user-attachments/assets/51bdb639-04af-401b-9d90-296833e4baaf)

### 运行环境

Windows 10 IoT 企业版 LTSC 21H2 19044.5011
Git:2.47.0
Nodjs:20.18.0
Hexo:7.3.0

### 主题配置文件

```yaml
跟仓库里的config.yml一样
```

**Comment by OcrSu** [comment]
仓库里的config.yml和模板仓库的config.yml不一样啊，要用模板仓库的配置文件才行
特此留下issue供其他人查阅

**Comment by Candinya** [comment]
感谢提示，我在 ReadMe 里补充一下 🙏
