### ISSUE TITLE
更新到1.4.4后，使用valine报错

### ISSUE THREAD

**Issue by sineatos** [Candinya/Kratos-Rebirth#28]
Hello~，我从1.4.3更新到1.4.4后，配置好valine，然后文章配置comments=true，本地启动hexo后爆下面的错误。

将comments设置为false后能正常进去文章的页面。

请问需要怎么解决？

```
Unhandled rejection Error: /Users/path/to/blog/themes/KratosRebirth/layout/post.ejs:83
    81|         <% } %>
    82|         <% if (theme.posts.comments && page.comments && page.title && !page.link) { %>
 >> 83|             <%- partial('_comments/' + theme.posts.comments) %>
    84|         <% } %>
    85|     </article>
    86| </section>

Partial _comments/vanila does not exist. (in post.ejs)
    at Object.partial (/Users/path/to/blog/node_modules/hexo/lib/plugins/helper/partial.js:16:11)
    at eval (/Users/path/to/blog/themes/KratosRebirth/layout/post.ejs:156:17)
    at post (/Users/path/to/blog/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiled (/Users/path/to/blog/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/Users/path/to/blog/node_modules/hexo/lib/theme/view.js:39:17)
    at /Users/path/to/blog/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/Users/path/to/blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/path/to/blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/path/to/blog/node_modules/hexo/lib/hexo/router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:469:10)
    at resume_ (_stream_readable.js:956:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by Candinya** [comment]
抱歉，是我的文档中错误地将`valine`拼成了~vanila~导致了误导呢，您在主题设置中修改为为`valine`应该就可以加载啦，抱歉给您带来了不便呢qwq

**Comment by sineatos** [comment]
可以用了，开心。谢谢~

**Comment by Candinya** [comment]
好耶！o(*￣▽￣*)ブ

**Comment by sineatos** [comment]
> 抱歉，是我的文档中错误地将`valine`拼成了~vanila~导致了误导呢，您在主题设置中修改为`valine`应该就可以加载啦，抱歉给您带来了不便呢qwq

可以用了，开心，谢谢~
